openapiOptions:
  method:
    - method: stores.proto.StoresService.CreateStore
      option:
        operationId: createStore
        tags:
          - Store
        summary: Create a new store
    - method: stores.proto.StoresService.GetStore
      option:
        operationId: getStore
        tags:
          - Store
        summary: Get store data
    - method: stores.proto.StoresService.EnableParticipation
      option:
        operationId: enableParticipation
        tags:
          - Store
        summary: Enable store service participation
