version: "3.8"

services:
  monolith:
    container_name: monolith
    hostname: monolith
    build:
      context: .
    ports:
      - '8080:8080'
      - '8085:8085'
    env_file:
      - .env
    depends_on:
      - nats
      - postgres
    command: ["./wait-for-it.sh", "postgres:5432", "--", "/mallbots/monolith"]
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: itsasecret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './database:/docker-entrypoint-initdb.d'
  nats:
    container_name: nats
    hostname: nats
    image: nats:2-alpine
    ports:
      - '4222:4222'
    command:
      - -js

volumes:
  pgdata:
