@startuml
!theme plain
skinparam dpi 400
skinparam defaultFontName Jetbrains Mono
skinparam ParticipantPadding 0

participant Producer as prod
queue "Message Broker" as b
participant Consumer as con

prod -> b : <b>1<sup>st</sup></b> Notification
prod -> b : <b>2<sup>nd</sup></b> Notification
b -->> con : <b>1<sup>st</sup></b> Notification

con -> prod ++ : <b>1<sup>st</sup></b> Callback
prod -> b : <b>3<sup>rd</sup></b> Notification
b -->> con : <b>2<sup>nd</sup></b> Notification
prod -> con --

con -> prod ++ : <b>2<sup>nd</sup></b> Callback
b -->> con : <b>3<sup>rd</sup></b> Notification
prod -> con --

con -> prod ++  : <b>3<sup>rd</sup></b> Callback
|||
prod -> con --

@enduml
