openapiOptions:
  method:
    - method: basketpb.BasketService.StartBasket
      option:
        operationId: createBasket
        tags:
          - Basket
        summary: Start a new shopping basket
    - method: basketpb.BasketService.GetBasket
      option:
        operationId: getBasket
        tags:
          - Basket
        summary: Get a basket
    - method: basketpb.BasketService.CancelBasket
      option:
        operationId: cancelBasket
        tags:
          - Basket
        summary: Cancel a shopping basket
    - method: basketpb.BasketService.CheckoutBasket
      option:
        operationId: checkoutBasket
        tags:
          - Basket
        summary: Checkout with a shopping basket
    - method: basketpb.BasketService.AddItem
      option:
        operationId: addItem
        tags:
          - Basket
          - Item
        summary: Add or add quantity to an item in the shopping basket
    - method: basketpb.BasketService.RemoveItem
      option:
        operationId: removeItem
        tags:
          - Basket
          - Item
        summary: Remove or remove quantity to an item in the shopping basket
