version: "3.8"
name: pact
services:
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: itsasecret
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './docker/database:/docker-entrypoint-initdb.d'
  pact:
    container_name: pact
    hostname: pact
    image: pactfoundation/pact-broker:2
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_DATABASE_URL: "postgres://pactuser:pactpass@postgres/pactdb"
      PACT_BROKER_BASIC_AUTH_USERNAME: pactuser
      PACT_BROKER_BASIC_AUTH_PASSWORD: pactpass
      PACT_BROKER_ALLOW_PUBLIC_READ: true
volumes:
  pgdata:
