name: Deploy Baskets

on:
  push:
    branches:
      - main
    paths:
      - baskets/**
      - internal/**
      - stores/storespb/**

env:
  SERVICE: baskets

jobs:
  build:
    name: Baskets microservice deployment to EKS cluster
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install kubectl
        id: kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build $SERVICE microservice
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
          GITHUB_SHA: ${{ github.sha }}
          DOCKERFILE: docker/Dockerfile.microservices
        run: |
          docker build -t $REGISTRY/$SERVICE:$GITHUB_SHA -t $REGISTRY/$SERVICE:latest --file $DOCKERFILE --build-arg=service=$SERVICE .
          docker push $REGISTRY/$SERVICE
